[workspace]
[package]
name = "third-party"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "/dev/null"

[dependencies]
anyhow = "1.0.75"
argh = "0.1.12"
convert_case = "0.6.0"
cxx = { version = "1.0.107", features = ["c++17"] }
minijinja = "1.0.8"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
thiserror = "1.0.48"
